import { readFileSync } from 'node:fs';
import { afterEach, describe, expect, it, vi } from 'vitest';

/*
 * The demo shim, pinned.
 *
 * Two things are worth a test here and they are different kinds of thing. One
 * is the shim's own judgement — which pages count as the demo, and what it does
 * with a file that has been mangled. The other is the committed file itself:
 * public/oh/demo.json is generated by hand-run script and read by four store
 * functions, so a regeneration that changes its shape should fail here rather
 * than on a prospect's phone.
 *
 * Everything is loaded through a fresh module instance because loadDemo
 * memoizes for the life of the page, which is the right behaviour there and
 * would make these tests depend on their own order.
 */

const DEMO_FILE = new URL('../../public/oh/demo.json', import.meta.url);
const committed = () => JSON.parse(readFileSync(DEMO_FILE, 'utf8')) as Record<string, unknown>;

type Page = { pathname?: string; search?: string };

const load = async (body: unknown, page: Page = {}) => {
  vi.resetModules();
  vi.stubGlobal('location', { pathname: page.pathname ?? '/oh/demo/', search: page.search ?? '' });
  vi.stubGlobal(
    'fetch',
    vi.fn(async () => ({ ok: true, json: async () => body })),
  );
  return import('./demo');
};

afterEach(() => {
  vi.unstubAllGlobals();
});

describe('which page is the demo', () => {
  it('knows the path, with or without the trailing slash', async () => {
    for (const pathname of ['/oh/demo', '/oh/demo/', '/oh/demo/index.html']) {
      const { isDemo } = await load(committed(), { pathname });
      expect(isDemo()).toBe(true);
    }
  });

  it('accepts ?demo as an alias, so a link cannot land on the directory', async () => {
    const { isDemo } = await load(committed(), { pathname: '/oh/', search: '?demo' });
    expect(isDemo()).toBe(true);
  });

  it('leaves every other page alone', async () => {
    for (const page of [
      { pathname: '/oh/' },
      { pathname: '/oh/demonstration/' },
      { pathname: '/oh/', search: '?manage' },
      { pathname: '/' },
    ]) {
      const { isDemo } = await load(committed(), page);
      expect(isDemo()).toBe(false);
    }
  });

  it('is false off a page altogether, which is where the tests run', async () => {
    vi.resetModules();
    vi.unstubAllGlobals();
    const { isDemo } = await import('./demo');
    expect(isDemo()).toBe(false);
  });
});

describe('the committed file', () => {
  it('reads as a demo, with the six sports the hub is sold on', async () => {
    const { loadDemo, DEMO_SLUG } = await load(committed());
    const demo = await loadDemo();

    expect(demo).not.toBeNull();
    expect(demo!.slug).toBe(DEMO_SLUG);
    expect(demo!.sportNames).toEqual([
      'football',
      'volleyball',
      'soccer',
      'basketball',
      'wrestling',
      'baseball',
    ]);
    // Every sport the hub will draw has a squad behind it, or the tile is a
    // dead tap.
    for (const sport of demo!.sportNames) {
      expect(demo!.sports[sport].players.length).toBeGreaterThan(0);
    }
  });

  it('carries a season for the school and for every conference member', async () => {
    const { loadDemo, demoSeason, DEMO_SLUG } = await load(committed());
    const demo = await loadDemo();
    const league = demo!.league as { members: string[] };

    for (const slug of [DEMO_SLUG, ...league.members]) {
      const season = await demoSeason(slug);
      expect(season, slug).not.toBeNull();
      expect(season!.games.length).toBeGreaterThan(0);
    }
  });

  it('agrees with itself about what the school has played', async () => {
    const { loadDemo, DEMO_SLUG } = await load(committed());
    const season = (await loadDemo())!.seasons[DEMO_SLUG];
    const played = season.games.filter((g) => g.result);

    expect(season.record.played).toBe(played.length);
    expect(season.record.won).toBe(played.filter((g) => g.result!.won).length);
    expect(season.record.lost).toBe(played.filter((g) => !g.result!.won).length);
    // A demo school that wins everything reads as a brochure rather than a
    // product, and both chips have to be on screen to be worth showing.
    expect(season.record.won).toBeGreaterThan(0);
    expect(season.record.lost).toBeGreaterThan(0);
  });

  it('files the forecast on a fixture that has not been played', async () => {
    const { loadDemo, DEMO_SLUG } = await load(committed());
    const demo = await loadDemo();
    const game = demo!.seasons[DEMO_SLUG].games.find((g) => g.date === demo!.weather!.date);

    expect(game).toBeDefined();
    expect(game!.result).toBeUndefined();
  });
});

describe('what the store guards ask for', () => {
  it('hangs the conference on football and on nothing else', async () => {
    const { demoRosterBody, DEMO_SLUG } = await load(committed());

    const football = (await demoRosterBody(DEMO_SLUG, 'football')) as Record<string, unknown>;
    expect(football.league).not.toBeNull();
    // Football's fixtures come from the season, exactly as a real paid
    // school's do — there is nothing pasted for it.
    expect(football.schedule).toBeNull();

    const basketball = (await demoRosterBody(DEMO_SLUG, 'basketball')) as Record<string, unknown>;
    expect(basketball.league).toBeNull();
    expect(Array.isArray(basketball.schedule)).toBe(true);
  });

  it('answers for the demo school only', async () => {
    const { demoRosterBody, demoIdentity, demoWeather } = await load(committed());

    expect(await demoRosterBody('poland-seminary-poland', 'football')).toBeNull();
    expect(await demoIdentity('poland-seminary-poland')).toBeNull();
    expect(await demoWeather('poland-seminary-poland')).toBeNull();
  });

  it('answers nothing for a sport the school does not sell', async () => {
    const { demoRosterBody, DEMO_SLUG } = await load(committed());
    expect(await demoRosterBody(DEMO_SLUG, 'bowling')).toBeNull();
  });

  it('has no kept identity until the file has landed', async () => {
    const { keptDemoIdentity, loadDemo, DEMO_SLUG } = await load(committed());

    expect(keptDemoIdentity(DEMO_SLUG)).toBeNull();
    await loadDemo();
    expect(keptDemoIdentity(DEMO_SLUG)).not.toBeNull();
  });
});

/*
 * The guards, from the store side.
 *
 * This block deliberately does not mock ./supa the way rosterStore.test.ts
 * does. The demo has to work in a build with no Supabase variables at all —
 * which is exactly how CI runs — and the guards sit above the supaAvailable
 * gate precisely so that it does. Getting a roster back here, with no database
 * configured and no rpc mocked, is that claim being demonstrated rather than
 * asserted.
 */
describe('the store, in demo mode', () => {
  const stores = async () => {
    const { DEMO_SLUG } = await import('./demo');
    return {
      DEMO_SLUG,
      store: await import('./store'),
      rosterStore: await import('./rosterStore'),
    };
  };

  it('serves the roster, the identity and the season out of the baked file', async () => {
    await load(committed());
    const { DEMO_SLUG, store, rosterStore } = await stores();

    const identity = await rosterStore.loadSchoolSports(DEMO_SLUG);
    expect(identity!.sports).toHaveLength(6);
    expect(identity!.colors).not.toBeNull();
    expect(identity!.logo).toMatch(/^data:image\/png;base64,/);

    const roster = await rosterStore.loadSchoolRoster(DEMO_SLUG, 'volleyball');
    expect(roster!.players).toHaveLength(12);
    expect(roster!.schedule).toHaveLength(9);
    // Only football carries a conference, and this one is volleyball.
    expect(roster!.league).toBeNull();

    const season = await store.loadSeason(DEMO_SLUG);
    expect(season.school.name).toBe('Springfield Local');

    const weather = await store.loadWeather(DEMO_SLUG);
    expect(weather!.date).toBe('2026-09-25');
  });

  it('leaves the kept-identity door where it was: null until the file lands', async () => {
    await load(committed());
    const { DEMO_SLUG, rosterStore } = await stores();

    expect(rosterStore.keptSchoolSports(DEMO_SLUG)).toBeNull();
    await rosterStore.loadSchoolSports(DEMO_SLUG);
    expect(rosterStore.keptSchoolSports(DEMO_SLUG)!.sports).toHaveLength(6);
  });

  it('resolves a conference member the same way, so the League tab can count', async () => {
    await load(committed());
    const { DEMO_SLUG, store, rosterStore } = await stores();

    const football = await rosterStore.loadSchoolRoster(DEMO_SLUG, 'football');
    const league = football!.league!;
    expect(league.members.length).toBeGreaterThanOrEqual(5);

    const { leagueTable } = await import('./leagueTable');
    const members = [DEMO_SLUG, ...league.members];
    const seasons = await Promise.all(members.map((m) => store.loadSeason(m)));
    const rows = leagueTable(seasons, members);

    // The whole conference or none of it — the rule School.tsx holds the tab
    // to. A demo that cannot fill its own table would ship a broken tab.
    expect(rows).toHaveLength(members.length);
    expect(rows.map((r) => r.slug)).toContain(DEMO_SLUG);
  });
});

describe('a file that is not what it should be', () => {
  const mangled: Array<[string, unknown]> = [
    ['not an object', 'nope'],
    ['no slug', { ...committed(), slug: '' }],
    ['no sport names', { ...committed(), sportNames: [] }],
    ['a sport with no squad', (() => {
      const c = committed() as { sportNames: string[]; sports: Record<string, unknown> };
      return { ...c, sports: { ...c.sports, football: { players: [], schedule: null } } };
    })()],
    ['a sport the names promise and the file has not got', (() => {
      const c = committed() as { sportNames: string[] };
      return { ...c, sportNames: [...c.sportNames, 'lacrosse'] };
    })()],
    ['a season with no games', (() => {
      const c = committed() as { slug: string; seasons: Record<string, unknown> };
      return { ...c, seasons: { ...c.seasons, [c.slug]: { school: {}, games: null } } };
    })()],
    ['no season for the school itself', (() => {
      const c = committed() as { slug: string; seasons: Record<string, unknown> };
      const seasons = { ...c.seasons };
      delete seasons[c.slug];
      return { ...c, seasons };
    })()],
  ];

  it.each(mangled)('reads %s as no demo rather than throwing', async (_label, body) => {
    const { loadDemo } = await load(body);
    await expect(loadDemo()).resolves.toBeNull();
  });

  it('drops a forecast it cannot trust without losing the demo with it', async () => {
    const { loadDemo } = await load({ ...committed(), weather: { date: '2026-09-25' } });
    const demo = await loadDemo();

    expect(demo).not.toBeNull();
    expect(demo!.weather).toBeNull();
  });

  it('reads a file that will not come at all as no demo', async () => {
    vi.resetModules();
    vi.stubGlobal('location', { pathname: '/oh/demo/', search: '' });
    vi.stubGlobal(
      'fetch',
      vi.fn(async () => {
        throw new Error('no signal');
      }),
    );
    const { loadDemo } = await import('./demo');
    await expect(loadDemo()).resolves.toBeNull();
  });
});
