import { readFileSync } from 'node:fs';
import { afterEach, describe, expect, it, vi } from 'vitest';
import { inSeason, knownSports } from './sportSeasons';

/*
 * The demo shim, pinned.
 *
 * Two things are worth a test here and they are different kinds of thing. One
 * is the shim's own judgement — which pages count as the demo, and what it does
 * with a file that has been mangled. The other is the committed file itself:
 * public/oh/demo.json is generated by hand-run script and read by four store
 * functions, so a regeneration that changes its shape should fail here rather
 * than on a prospect's phone.
 *
 * Everything is loaded through a fresh module instance because loadDemo
 * memoizes for the life of the page, which is the right behaviour there and
 * would make these tests depend on their own order.
 */

const DEMO_FILE = new URL('../../public/oh/demo.json', import.meta.url);
const committed = () => JSON.parse(readFileSync(DEMO_FILE, 'utf8')) as Record<string, unknown>;

type Page = { pathname?: string; search?: string };

const load = async (body: unknown, page: Page = {}) => {
  vi.resetModules();
  vi.stubGlobal('location', { pathname: page.pathname ?? '/oh/demo/', search: page.search ?? '' });
  vi.stubGlobal(
    'fetch',
    vi.fn(async () => ({ ok: true, json: async () => body })),
  );
  return import('./demo');
};

afterEach(() => {
  vi.unstubAllGlobals();
});

describe('which page is the demo', () => {
  it('knows the path, with or without the trailing slash', async () => {
    for (const pathname of ['/oh/demo', '/oh/demo/', '/oh/demo/index.html']) {
      const { isDemo } = await load(committed(), { pathname });
      expect(isDemo()).toBe(true);
    }
  });

  it('accepts ?demo as an alias, so a link cannot land on the directory', async () => {
    for (const search of ['?demo', '?demo=1', '?demo=yes']) {
      const { isDemo } = await load(committed(), { pathname: '/oh/', search });
      expect(isDemo(), search).toBe(true);
    }
  });

  it('reads ?demo=false as somebody turning it off', async () => {
    for (const search of ['?demo=false', '?demo=0', '?demo=no', '?demo=OFF']) {
      const { isDemo } = await load(committed(), { pathname: '/oh/', search });
      expect(isDemo(), search).toBe(false);
    }
  });

  it('leaves every other page alone', async () => {
    for (const page of [
      { pathname: '/oh/' },
      { pathname: '/oh/demonstration/' },
      { pathname: '/oh/', search: '?manage' },
      { pathname: '/' },
    ]) {
      const { isDemo } = await load(committed(), page);
      expect(isDemo()).toBe(false);
    }
  });

  it('is false off a page altogether, which is where the tests run', async () => {
    vi.resetModules();
    vi.unstubAllGlobals();
    const { isDemo } = await import('./demo');
    expect(isDemo()).toBe(false);
  });
});

/*
 * Whether the file was written with the autumn on.
 *
 * The generator has two honest outputs and they look nothing alike. Written
 * between August and November it produces a season under way — half played,
 * a record, a standings table. Written between December and July it produces
 * the next autumn as fixtures with **nothing** played, because a season cannot
 * both carry results and sit in months eight to eleven when today is February,
 * and the hub would otherwise print "Starts in August" over a row of January
 * scores.
 *
 * So "no results anywhere" is a correct file half the year and a broken one the
 * other half, and the tests below have to ask which half before they judge. The
 * day it was written is on the file for exactly this reason.
 */
const bornInSeason = (): boolean =>
  inSeason('football', Number((committed() as { generatedOn: string }).generatedOn.slice(5, 7)));

describe('the committed file', () => {
  it('reads as a demo, with the six sports the hub is sold on', async () => {
    const { loadDemo, DEMO_SLUG } = await load(committed());
    const demo = await loadDemo();

    expect(demo).not.toBeNull();
    expect(demo!.slug).toBe(DEMO_SLUG);
    expect(demo!.sportNames).toEqual([
      'football',
      'volleyball',
      'soccer',
      'basketball',
      'wrestling',
      'baseball',
    ]);
    // Every sport the hub will draw has a squad behind it, or the tile is a
    // dead tap.
    for (const sport of demo!.sportNames) {
      expect(demo!.sports[sport].players.length).toBeGreaterThan(0);
    }
  });

  it('carries a season for the school and for every conference member', async () => {
    const { loadDemo, demoSeason, DEMO_SLUG } = await load(committed());
    const demo = await loadDemo();
    const league = demo!.league as { members: string[] };

    for (const slug of [DEMO_SLUG, ...league.members]) {
      const season = await demoSeason(slug);
      expect(season, slug).not.toBeNull();
      expect(season!.games.length).toBeGreaterThan(0);
    }
  });

  it('agrees with itself about what the school has played', async () => {
    const { loadDemo, DEMO_SLUG } = await load(committed());
    const season = (await loadDemo())!.seasons[DEMO_SLUG];
    const played = season.games.filter((g) => g.result);

    expect(season.record.played).toBe(played.length);
    expect(season.record.won).toBe(played.filter((g) => g.result!.won).length);
    expect(season.record.lost).toBe(played.filter((g) => !g.result!.won).length);

    // Only a file written in the autumn owes anybody a record. When it is, a
    // demo school that wins everything reads as a brochure rather than a
    // product, so both chips have to be on screen. Out of season 0–0 is the
    // true answer and the school's own page would say so.
    if (bornInSeason()) {
      expect(season.record.won).toBeGreaterThan(0);
      expect(season.record.lost).toBeGreaterThan(0);
    } else {
      expect(season.record.played).toBe(0);
    }
  });

  it('files the forecast on the next fixture, which has not been played', async () => {
    const { loadDemo, DEMO_SLUG } = await load(committed());
    const demo = await loadDemo();
    const games = demo!.seasons[DEMO_SLUG].games;
    const next = games.find((g) => !g.result);

    // Not merely "some unplayed game": School.tsx draws a forecast on the
    // fixture naming that same date and on no other, so a forecast pointed at
    // week nine would silently print nothing.
    expect(demo!.weather!.date).toBe(next!.date);
  });

  /*
   * The invariant the generator is anchored to produce: a score is only ever
   * printed on a day that has been.
   *
   * Checked as an ordering rather than against the clock, deliberately. The
   * file is static and drifts — five weeks after a generation the last autumn
   * fixture has gone by with no score on it — and a test that read `new Date()`
   * would turn that expected drift into a red build. What must never be true,
   * at any distance from the generation, is a scored game dated after an
   * unscored one; that is a generator bug rather than staleness.
   */
  it('puts every result behind every fixture, in all six seasons', async () => {
    const { loadDemo } = await load(committed());
    const demo = await loadDemo();

    for (const [slug, season] of Object.entries(demo!.seasons)) {
      const scored = season.games.filter((g) => g.result).map((g) => g.date);
      const ahead = season.games.filter((g) => !g.result).map((g) => g.date);
      // Results only when the autumn was on — see bornInSeason above. Fixtures
      // always: a season with nothing to come is not a page worth opening.
      expect(scored.length > 0, slug).toBe(bornInSeason());
      expect(ahead.length, slug).toBeGreaterThan(0);
      // ISO dates sort as strings, so this is the whole comparison.
      expect(scored.every((s) => ahead.every((a) => s < a)), slug).toBe(true);
    }
  });

  it('puts every result behind every fixture in the pasted schedules too', async () => {
    const { loadDemo } = await load(committed());
    const demo = await loadDemo();

    for (const [sport, entry] of Object.entries(demo!.sports)) {
      const rows = entry.schedule ?? [];
      const scored = rows.filter((r) => r.score).map((r) => r.date);
      const ahead = rows.filter((r) => !r.score).map((r) => r.date);
      expect(scored.every((s) => ahead.every((a) => s < a)), sport).toBe(true);
    }
  });

  /*
   * The file is generated in one sport-season and read in another, and the hub
   * prints "In season" or "Starts in November" out of its own fixed table. This
   * holds the committed dates to that table as it stood on the day they were
   * written — `generatedOn`, rather than the clock the suite happens to run on,
   * because the file is static and the point is what the generator produced.
   */
  it('never writes a season the hub would contradict', () => {
    // Read straight off the committed file rather than through loadDemo, which
    // carries the dates forward to today — what is being checked here is what
    // the generator wrote, on the day it wrote it.
    const raw = committed() as unknown as {
      generatedOn: string;
      seasons: Record<string, { games: Array<{ date: string; result?: unknown }> }>;
      sports: Record<string, { schedule: Array<{ date: string; score?: unknown }> | null }>;
    };
    const month = Number(raw.generatedOn.slice(5, 7));

    const dates: Array<[string, string, boolean]> = [];
    for (const season of Object.values(raw.seasons)) {
      for (const g of season.games) dates.push(['football', g.date, !!g.result]);
    }
    for (const [sport, entry] of Object.entries(raw.sports)) {
      for (const r of entry.schedule ?? []) dates.push([sport, r.date, !!r.score]);
    }

    for (const [sport, date, scored] of dates) {
      if (inSeason(sport, month)) continue;
      // Out of season on the day it was written, a sport may have no results
      // and may only be dated inside its own months — the alternative is
      // "Starts in August" printed over a row of January scores.
      expect(scored, `${sport} ${date}`).toBe(false);
      expect(inSeason(sport, Number(date.slice(5, 7))), `${sport} ${date}`).toBe(true);
    }
  });

  /*
   * The generator is a .mjs script that cannot import this bundle's TypeScript,
   * so it keeps its own copy of the month table and this holds the two
   * together. Read out of the source text rather than imported, because
   * importing the script runs it — it rasterizes a crest and writes a file.
   */
  it('keeps the generator’s copy of the month table honest', () => {
    const src = readFileSync(new URL('../../scripts/build-demo.mjs', import.meta.url), 'utf8');
    const block = src.match(/const SPORT_MONTHS = \{([\s\S]*?)\n\};/);
    expect(block, 'SPORT_MONTHS is no longer where this test looks for it').not.toBeNull();

    const rows = [...block![1].matchAll(/^\s*(\w+): \[([\d, ]+)\],$/gm)];
    expect(rows.length).toBeGreaterThan(0);

    for (const [, sport, list] of rows) {
      expect(knownSports(), sport).toContain(sport);
      const copied = list.split(',').map((n) => Number(n.trim()));
      for (let month = 1; month <= 12; month += 1) {
        expect(copied.includes(month), `${sport} month ${month}`).toBe(inSeason(sport, month));
      }
    }
  });

  it('keeps every rival on the same ten dates as the school', async () => {
    const { loadDemo, DEMO_SLUG } = await load(committed());
    const demo = await loadDemo();
    const ours = demo!.seasons[DEMO_SLUG].games.map((g) => g.date);

    // A rival left on an older calendar would still fill its row, and the
    // standings would quietly stop agreeing with the school's own record.
    for (const [slug, season] of Object.entries(demo!.seasons)) {
      expect(season.games.map((g) => g.date), slug).toEqual(ours);
    }
  });
});

/*
 * Carrying the calendar forward.
 *
 * The file is committed and then sits still while the world moves, and the
 * screen splits Played from Coming up on whether a game has a score rather than
 * on its date — so without this the demo starts listing last Friday's game as
 * coming up. These are the only tests here that name a day, and they name a
 * made-up one rather than reading the clock.
 */
describe('the calendar, weeks after it was written', () => {
  const day = (iso: string) => new Date(`${iso}T00:00:00Z`);

  const everyDate = (demo: {
    seasons: Record<string, { games: Array<{ date: string; result?: unknown }> }>;
    sports: Record<string, { schedule: Array<{ date: string; score?: unknown }> | null }>;
  }) => {
    const all: Array<[string, boolean]> = [];
    for (const season of Object.values(demo.seasons)) {
      for (const g of season.games) all.push([g.date, !!g.result]);
    }
    for (const entry of Object.values(demo.sports)) {
      for (const r of entry.schedule ?? []) all.push([r.date, !!r.score]);
    }
    return all;
  };

  it('lands the split on today, however long the file has sat', async () => {
    const { loadDemo, shiftToNow } = await load(committed());
    const demo = await loadDemo();

    for (const when of ['2026-09-14', '2027-01-02', '2027-06-30', '2029-03-05']) {
      const moved = shiftToNow(demo!, day(when));
      for (const [date, scored] of everyDate(moved)) {
        if (scored) expect(date < when, `${when}: ${date} has a score`).toBe(true);
        else expect(date >= when, `${when}: ${date} has no score`).toBe(true);
      }
    }
  });

  it('moves whole weeks, so Friday football stays on a Friday', async () => {
    const { loadDemo, shiftToNow, DEMO_SLUG } = await load(committed());
    const demo = await loadDemo();
    const before = demo!.seasons[DEMO_SLUG].games.map((g) => g.date);
    const after = shiftToNow(demo!, day('2027-06-30')).seasons[DEMO_SLUG].games.map((g) => g.date);

    for (let i = 0; i < before.length; i += 1) {
      expect(day(after[i]).getUTCDay(), before[i]).toBe(day(before[i]).getUTCDay());
      const weeks = (day(after[i]).getTime() - day(before[i]).getTime()) / (7 * 86_400_000);
      expect(Number.isInteger(weeks), before[i]).toBe(true);
    }
  });

  it('moves all six seasons by the same amount, or the standings stop agreeing', async () => {
    const { loadDemo, shiftToNow, DEMO_SLUG } = await load(committed());
    const demo = await loadDemo();
    const moved = shiftToNow(demo!, day('2027-06-30'));

    const ours = moved.seasons[DEMO_SLUG].games.map((g) => g.date);
    for (const [slug, season] of Object.entries(moved.seasons)) {
      expect(season.games.map((g) => g.date), slug).toEqual(ours);
    }
    // The record is a count, so it cannot move — but it still has to agree with
    // the games after the shift, which is what the League tab reads.
    const played = moved.seasons[DEMO_SLUG].games.filter((g) => g.result);
    expect(moved.seasons[DEMO_SLUG].record.played).toBe(played.length);
    expect(moved.seasons[DEMO_SLUG].record.won).toBe(played.filter((g) => g.result!.won).length);
  });

  it('carries the forecast along with the fixture it belongs to', async () => {
    const { loadDemo, shiftToNow, DEMO_SLUG } = await load(committed());
    const moved = shiftToNow((await loadDemo())!, day('2027-01-02'));
    const next = moved.seasons[DEMO_SLUG].games.find((g) => !g.result);

    expect(moved.weather!.date).toBe(next!.date);
    expect(moved.weather!.at.startsWith(next!.date)).toBe(true);
  });

  it('leaves a file generated today exactly as it is', async () => {
    const born = (committed() as { generatedOn: string }).generatedOn;
    const { loadDemo, shiftToNow, weeksBehind } = await load(committed());
    const demo = await loadDemo();

    // Keyed on the day it was written rather than on its last result, because
    // a file written out of season has no results to key on.
    expect(weeksBehind(demo!, day(born))).toBe(0);
    expect(shiftToNow(demo!, day(born))).toBe(demo);
  });

  /*
   * The other kind of file: written between December and July, when the autumn
   * has not begun, so the generator writes every game as a fixture and nothing
   * as a result. It has no last-played day, and hinging on nothing used to mean
   * never moving — its fixtures would slide into the past one at a time and sit
   * there under "Coming up", which is the whole fault this is here to prevent.
   *
   * Made by stripping the scores off the committed file rather than by shipping
   * a second one, so it stays honest whichever half of the year the real file
   * was generated in.
   */
  const scoreless = () => {
    const raw = committed() as unknown as {
      seasons: Record<string, { games: Array<Record<string, unknown>> }>;
      sports: Record<string, { schedule: Array<Record<string, unknown>> | null }>;
    };
    for (const season of Object.values(raw.seasons)) {
      for (const g of season.games) delete g.result;
    }
    for (const entry of Object.values(raw.sports)) {
      for (const r of entry.schedule ?? []) delete r.score;
    }
    return raw as unknown as Record<string, unknown>;
  };

  it('still moves a file with nothing played on it', async () => {
    const { loadDemo, shiftToNow, weeksBehind } = await load(scoreless());
    const demo = await loadDemo();

    for (const when of ['2027-03-01', '2027-11-11', '2030-01-20']) {
      const moved = shiftToNow(demo!, day(when));
      expect(weeksBehind(demo!, day(when)), when).toBeGreaterThan(0);
      for (const [date, scored] of everyDate(moved)) {
        expect(scored, `${when}: ${date}`).toBe(false);
        expect(date >= when, `${when}: ${date} is behind today`).toBe(true);
      }
    }
  });

  it('moves a scoreless file by whole weeks, all seasons together', async () => {
    const { loadDemo, shiftToNow, DEMO_SLUG } = await load(scoreless());
    const demo = await loadDemo();
    const before = demo!.seasons[DEMO_SLUG].games.map((g) => g.date);
    const moved = shiftToNow(demo!, day('2027-11-11'));
    const after = moved.seasons[DEMO_SLUG].games.map((g) => g.date);

    for (let i = 0; i < before.length; i += 1) {
      const weeks = (day(after[i]).getTime() - day(before[i]).getTime()) / (7 * 86_400_000);
      expect(Number.isInteger(weeks), before[i]).toBe(true);
      expect(day(after[i]).getUTCDay(), before[i]).toBe(day(before[i]).getUTCDay());
    }
    for (const [slug, season] of Object.entries(moved.seasons)) {
      expect(season.games.map((g) => g.date), slug).toEqual(after);
    }
    expect(moved.weather!.at.startsWith(moved.weather!.date)).toBe(true);
  });

  it('does not drag a scoreless file backwards either', async () => {
    const { loadDemo, weeksBehind } = await load(scoreless());
    expect(weeksBehind((await loadDemo())!, day('2020-01-01'))).toBe(0);
  });

  it('never drags a file backwards for a clock that is behind', async () => {
    const { loadDemo, weeksBehind } = await load(committed());
    expect(weeksBehind((await loadDemo())!, day('2020-01-01'))).toBe(0);
  });
});

describe('what the store guards ask for', () => {
  it('hangs the conference on football and on nothing else', async () => {
    const { demoRosterBody, DEMO_SLUG } = await load(committed());

    const football = (await demoRosterBody(DEMO_SLUG, 'football')) as Record<string, unknown>;
    expect(football.league).not.toBeNull();
    // Football's fixtures come from the season, exactly as a real paid
    // school's do — there is nothing pasted for it.
    expect(football.schedule).toBeNull();

    const basketball = (await demoRosterBody(DEMO_SLUG, 'basketball')) as Record<string, unknown>;
    expect(basketball.league).toBeNull();
    expect(Array.isArray(basketball.schedule)).toBe(true);
  });

  it('answers for the demo school only', async () => {
    const { demoRosterBody, demoIdentity, demoWeather } = await load(committed());

    expect(await demoRosterBody('poland-seminary-poland', 'football')).toBeNull();
    expect(await demoIdentity('poland-seminary-poland')).toBeNull();
    expect(await demoWeather('poland-seminary-poland')).toBeNull();
  });

  it('answers nothing for a sport the school does not sell', async () => {
    const { demoRosterBody, DEMO_SLUG } = await load(committed());
    expect(await demoRosterBody(DEMO_SLUG, 'bowling')).toBeNull();
  });

  it('has no kept identity until the file has landed', async () => {
    const { keptDemoIdentity, loadDemo, DEMO_SLUG } = await load(committed());

    expect(keptDemoIdentity(DEMO_SLUG)).toBeNull();
    await loadDemo();
    expect(keptDemoIdentity(DEMO_SLUG)).not.toBeNull();
  });
});

/*
 * The guards, from the store side.
 *
 * This block deliberately does not mock ./supa the way rosterStore.test.ts
 * does. The demo has to work in a build with no Supabase variables at all —
 * which is exactly how CI runs — and the guards sit above the supaAvailable
 * gate precisely so that it does. Getting a roster back here, with no database
 * configured and no rpc mocked, is that claim being demonstrated rather than
 * asserted.
 */
describe('the store, in demo mode', () => {
  const stores = async () => {
    const { DEMO_SLUG } = await import('./demo');
    return {
      DEMO_SLUG,
      store: await import('./store'),
      rosterStore: await import('./rosterStore'),
    };
  };

  it('serves the roster, the identity and the season out of the baked file', async () => {
    await load(committed());
    const { DEMO_SLUG, store, rosterStore } = await stores();

    const identity = await rosterStore.loadSchoolSports(DEMO_SLUG);
    expect(identity!.sports).toHaveLength(6);
    expect(identity!.colors).not.toBeNull();
    expect(identity!.logo).toMatch(/^data:image\/png;base64,/);

    const roster = await rosterStore.loadSchoolRoster(DEMO_SLUG, 'volleyball');
    expect(roster!.players).toHaveLength(12);
    expect(roster!.schedule).toHaveLength(9);
    // Only football carries a conference, and this one is volleyball.
    expect(roster!.league).toBeNull();

    const season = await store.loadSeason(DEMO_SLUG);
    expect(season.school.name).toBe('Springfield Local');

    const weather = await store.loadWeather(DEMO_SLUG);
    expect(weather!.date).toBe(season.games.find((g) => !g.result)!.date);
  });

  it('leaves the kept-identity door where it was: null until the file lands', async () => {
    await load(committed());
    const { DEMO_SLUG, rosterStore } = await stores();

    expect(rosterStore.keptSchoolSports(DEMO_SLUG)).toBeNull();
    await rosterStore.loadSchoolSports(DEMO_SLUG);
    expect(rosterStore.keptSchoolSports(DEMO_SLUG)!.sports).toHaveLength(6);
  });

  it('refuses to remember a sport, so every prospect gets the hub', async () => {
    await load(committed());
    const { DEMO_SLUG, store } = await stores();
    const jar: Record<string, string> = {};
    vi.stubGlobal('localStorage', {
      getItem: (k: string) => jar[k] ?? null,
      setItem: (k: string, v: string) => {
        jar[k] = v;
      },
      removeItem: (k: string) => {
        delete jar[k];
      },
    });

    // What a seller tapping Volleyball to show a prospect does. It must leave
    // nothing behind: the hub is the screen the demo opens on, and the key
    // would outlive the visit anyway — choose()'s sweep only evicts the school
    // a reader was following, and nobody follows the demo.
    store.rememberSport(DEMO_SLUG, 'volleyball');
    expect(Object.keys(jar)).toEqual([]);
    expect(store.chosenSport(DEMO_SLUG)).toBeNull();

    // A key from some earlier build is not read either.
    jar[`oh.sport.${DEMO_SLUG}`] = 'basketball';
    expect(store.chosenSport(DEMO_SLUG)).toBeNull();
  });

  it('resolves a conference member the same way, so the League tab can count', async () => {
    await load(committed());
    const { DEMO_SLUG, store, rosterStore } = await stores();

    const football = await rosterStore.loadSchoolRoster(DEMO_SLUG, 'football');
    const league = football!.league!;
    expect(league.members.length).toBeGreaterThanOrEqual(5);

    const { leagueTable } = await import('./leagueTable');
    const members = [DEMO_SLUG, ...league.members];
    const seasons = await Promise.all(members.map((m) => store.loadSeason(m)));
    const rows = leagueTable(seasons, members);

    // The whole conference or none of it — the rule School.tsx holds the tab
    // to. A demo that cannot fill its own table would ship a broken tab.
    expect(rows).toHaveLength(members.length);
    expect(rows.map((r) => r.slug)).toContain(DEMO_SLUG);
  });
});

describe('a file that is not what it should be', () => {
  const mangled: Array<[string, unknown]> = [
    ['not an object', 'nope'],
    ['no slug', { ...committed(), slug: '' }],
    ['no sport names', { ...committed(), sportNames: [] }],
    ['a sport with no squad', (() => {
      const c = committed() as { sportNames: string[]; sports: Record<string, unknown> };
      return { ...c, sports: { ...c.sports, football: { players: [], schedule: null } } };
    })()],
    ['a sport the names promise and the file has not got', (() => {
      const c = committed() as { sportNames: string[] };
      return { ...c, sportNames: [...c.sportNames, 'lacrosse'] };
    })()],
    ['a season with no games', (() => {
      const c = committed() as { slug: string; seasons: Record<string, unknown> };
      return { ...c, seasons: { ...c.seasons, [c.slug]: { school: {}, games: null } } };
    })()],
    ['no season for the school itself', (() => {
      const c = committed() as { slug: string; seasons: Record<string, unknown> };
      const seasons = { ...c.seasons };
      delete seasons[c.slug];
      return { ...c, seasons };
    })()],
  ];

  it.each(mangled)('reads %s as no demo rather than throwing', async (_label, body) => {
    const { loadDemo } = await load(body);
    await expect(loadDemo()).resolves.toBeNull();
  });

  it('drops a forecast it cannot trust without losing the demo with it', async () => {
    const { loadDemo } = await load({ ...committed(), weather: { date: '2026-09-25' } });
    const demo = await loadDemo();

    expect(demo).not.toBeNull();
    expect(demo!.weather).toBeNull();
  });

  it('reads a file that will not come at all as no demo', async () => {
    vi.resetModules();
    vi.stubGlobal('location', { pathname: '/oh/demo/', search: '' });
    vi.stubGlobal(
      'fetch',
      vi.fn(async () => {
        throw new Error('no signal');
      }),
    );
    const { loadDemo } = await import('./demo');
    await expect(loadDemo()).resolves.toBeNull();
  });
});
