import { existsSync, readFileSync } from 'node:fs';
import { afterEach, describe, expect, it, vi } from 'vitest';
import { inSeason, knownSports } from './sportSeasons';

/*
 * The demo shim, pinned.
 *
 * Two things are worth a test here and they are different kinds of thing. One
 * is the shim's own judgement — which pages count as the demo, and what it does
 * with a file that has been mangled. The other is the committed file itself:
 * public/oh/demo.json is generated by hand-run script and read by four store
 * functions, so a regeneration that changes its shape should fail here rather
 * than on a prospect's phone.
 *
 * Everything is loaded through a fresh module instance because loadDemo
 * memoizes for the life of the page, which is the right behaviour there and
 * would make these tests depend on their own order.
 */

const DEMO_FILE = new URL('../../public/oh/demo.json', import.meta.url);
const committed = () => JSON.parse(readFileSync(DEMO_FILE, 'utf8')) as Record<string, unknown>;

const dataFile = (slug: string) => new URL(`../../public/oh/data/${slug}.json`, import.meta.url);
const directoryIndex = () =>
  JSON.parse(readFileSync(new URL('../../public/oh/index.json', import.meta.url), 'utf8')) as {
    schools: Array<{ slug: string; name: string }>;
  };

/** The conference the seller typed in, by exact directory slug. */
const MVAC_SCARLET = [
  'mcdonald-mcdonald',
  'jackson-milton-north-jackson',
  'campbell-memorial-campbell',
  'mineral-ridge-mineral-ridge',
  'lowellville-lowellville',
  'waterloo-atwater',
  'western-reserve-berlin-center',
];

type Page = { pathname?: string; search?: string };

/*
 * A stand-in for this origin.
 *
 * The demo file comes from the body given, and everything the demo does not
 * bake comes from where the page itself would get it: a season from the
 * committed directory file on disk, the forecast from whatever `weather` says.
 * That is the new contract being exercised rather than mocked around — the
 * school's football and its rivals' are the directory's.
 */
const load = async (body: unknown, page: Page = {}, weather: unknown = {}) => {
  vi.resetModules();
  vi.stubGlobal('location', { pathname: page.pathname ?? '/oh/demo/', search: page.search ?? '' });
  const jar: Record<string, string> = {};
  vi.stubGlobal('localStorage', {
    getItem: (k: string) => jar[k] ?? null,
    setItem: (k: string, v: string) => {
      jar[k] = v;
    },
    removeItem: (k: string) => {
      delete jar[k];
    },
  });
  vi.stubGlobal(
    'fetch',
    vi.fn(async (url: string) => {
      const path = String(url).split('?')[0];
      if (path === '/oh/demo.json') return { ok: true, json: async () => body };
      if (path === '/oh/weather.json') return { ok: true, json: async () => weather };
      const season = path.match(/^\/oh\/data\/([a-z0-9-]+)\.json$/);
      if (season && existsSync(dataFile(season[1]))) {
        const raw = readFileSync(dataFile(season[1]), 'utf8');
        return { ok: true, json: async () => JSON.parse(raw) };
      }
      return { ok: false, json: async () => null };
    }),
  );
  return import('./demo');
};

afterEach(() => {
  vi.unstubAllGlobals();
});

describe('which page is the demo', () => {
  it('knows the path, with or without the trailing slash', async () => {
    for (const pathname of ['/oh/demo', '/oh/demo/', '/oh/demo/index.html']) {
      const { isDemo } = await load(committed(), { pathname });
      expect(isDemo()).toBe(true);
    }
  });

  it('accepts ?demo as an alias, so a link cannot land on the directory', async () => {
    for (const search of ['?demo', '?demo=1', '?demo=yes']) {
      const { isDemo } = await load(committed(), { pathname: '/oh/', search });
      expect(isDemo(), search).toBe(true);
    }
  });

  it('reads ?demo=false as somebody turning it off', async () => {
    for (const search of ['?demo=false', '?demo=0', '?demo=no', '?demo=OFF']) {
      const { isDemo } = await load(committed(), { pathname: '/oh/', search });
      expect(isDemo(), search).toBe(false);
    }
  });

  it('leaves every other page alone', async () => {
    for (const page of [
      { pathname: '/oh/' },
      { pathname: '/oh/demonstration/' },
      { pathname: '/oh/', search: '?manage' },
      { pathname: '/' },
    ]) {
      const { isDemo } = await load(committed(), page);
      expect(isDemo()).toBe(false);
    }
  });

  it('is false off a page altogether, which is where the tests run', async () => {
    vi.resetModules();
    vi.unstubAllGlobals();
    const { isDemo } = await import('./demo');
    expect(isDemo()).toBe(false);
  });
});

/*
 * Whether the file was written with the autumn on.
 *
 * The generator has two honest outputs and they look nothing alike. Written
 * between August and November it produces a volleyball season under way — half
 * played, half to come. Written between December and July it produces the
 * next autumn as fixtures with **nothing** played, because a season cannot both
 * carry results and sit in months eight to eleven when today is February, and
 * the hub would otherwise print "Starts in August" over a row of January scores.
 *
 * So "no results anywhere" is a correct file half the year and a broken one the
 * other half, and the tests below have to ask which half before they judge. The
 * day it was written is on the file for exactly this reason.
 */
const bornInSeason = (): boolean =>
  inSeason('volleyball', Number((committed() as { generatedOn: string }).generatedOn.slice(5, 7)));

describe('the committed file', () => {
  it('reads as the Springfield demo, with the three sports the video sells', async () => {
    const { loadDemo, DEMO_SLUG } = await load(committed());
    const demo = await loadDemo();

    expect(demo).not.toBeNull();
    expect(DEMO_SLUG).toBe('springfield-new-middletown');
    expect(demo!.slug).toBe(DEMO_SLUG);
    expect(demo!.school).toEqual({
      slug: DEMO_SLUG,
      name: 'Springfield',
      city: 'New Middletown',
    });
    expect(demo!.sportNames).toEqual(['football', 'volleyball', 'basketball']);
    // Every sport the hub will draw has a squad behind it, or the tile is a
    // dead tap.
    for (const sport of demo!.sportNames) {
      expect(demo!.sports[sport].players.length).toBeGreaterThan(0);
    }
  });

  it('wears the video’s colors and a crest the database would have accepted', () => {
    const raw = committed() as { colors: unknown; logo: string };
    expect(raw.colors).toEqual({ ground: '#0e0c0b', accent: '#f26722' });
    // A JPEG, because that is what the panel's resizeLogo makes of an upload.
    expect(raw.logo).toMatch(/^data:image\/jpeg;base64,/);
    // The theme ceiling in 0005_school_theme.sql: a crest past it is one the
    // seller could never have stored for a real school.
    expect(raw.logo.length).toBeLessThan(500_000);
  });

  /*
   * The contract that makes the football half real: nothing about it is baked.
   * A season or a forecast in this file would be served in place of the
   * directory's, and would be wrong by the next Saturday refresh.
   */
  it('bakes no season and no forecast, so football and weather are the directory’s', async () => {
    const raw = committed();
    expect(raw.seasons).toBeUndefined();
    expect(raw.weather).toBeUndefined();

    const { loadDemo, demoSeason, demoWeather, DEMO_SLUG } = await load(committed());
    const demo = await loadDemo();
    const league = demo!.league as { members: string[] };
    for (const slug of [DEMO_SLUG, ...league.members]) {
      expect(await demoSeason(slug), slug).toBeNull();
    }
    expect(await demoWeather(DEMO_SLUG)).toBeNull();
    expect(demo!.sports.football.schedule).toBeNull();
  });

  it('names MVAC Scarlet by real directory slugs that Springfield actually plays', () => {
    const raw = committed() as { slug: string; league: { name: string; members: string[] } };
    expect(raw.league.name).toBe('MVAC Scarlet');
    expect([...raw.league.members].sort()).toEqual([...MVAC_SCARLET].sort());

    const known = new Set(directoryIndex().schools.map((s) => s.slug));
    const ours = JSON.parse(readFileSync(dataFile(raw.slug), 'utf8')) as {
      games: Array<{ opponentSlug: string | null }>;
    };
    for (const slug of raw.league.members) {
      expect(known.has(slug), slug).toBe(true);
      expect(existsSync(dataFile(slug)), slug).toBe(true);
      // A member Springfield never meets would sit in the table at 0–0
      // against the school being sold to.
      expect(ours.games.some((g) => g.opponentSlug === slug), slug).toBe(true);
    }
  });

  /*
   * The football roster is the video's, name for name, because a prospect who
   * has just watched #24 break free will type 24.
   */
  it('puts the video’s players on the football roster, and no stats on anybody', () => {
    const raw = committed() as {
      sports: Record<string, { players: Array<Record<string, unknown>> }>;
    };
    const football = raw.sports.football.players;
    const byNumber = new Map(football.map((p) => [p.number, p]));

    expect(byNumber.get('24')).toMatchObject({
      firstName: 'Marcus',
      lastName: 'Bell',
      position: 'RB/LB',
      grade: 'Sr',
      heightIn: 71,
      weightLb: 195,
    });
    const named: Array<[string, string, string]> = [
      ['1', 'Owen', 'Carter'],
      ['2', 'Jalen', 'Reyes'],
      ['3', 'Eli', 'Novak'],
      ['4', 'Drew', 'Halloran'],
      ['5', 'Kai', 'Mercer'],
      ['6', 'Sam', 'Whitfield'],
      ['7', 'Tobias', 'Kerr'],
      ['10', 'Caleb', 'Ostrowski'],
      ['11', 'Nate', 'Pryor'],
      ['12', 'Luke', 'Danner'],
      ['14', 'Isaac', 'Moreno'],
      ['15', 'Grant', 'Yoder'],
    ];
    for (const [number, firstName, lastName] of named) {
      expect(byNumber.get(number), number).toMatchObject({ firstName, lastName });
    }
    // A believable small-school varsity, not a sketch.
    expect(football.length).toBeGreaterThanOrEqual(25);
    expect(new Set(football.map((p) => p.number)).size).toBe(football.length);

    // The app has no stats, so the demo must not smuggle any in.
    for (const [sport, entry] of Object.entries(raw.sports)) {
      for (const p of entry.players) {
        expect(Object.keys(p).some((k) => /stat/i.test(k)), `${sport} #${p.number}`).toBe(false);
      }
    }
    expect(raw.sports.volleyball.players.length).toBeGreaterThanOrEqual(10);
    expect(raw.sports.basketball.players.length).toBeGreaterThanOrEqual(10);
  });

  it('pastes schedules against the real conference’s names', () => {
    const raw = committed() as {
      sports: Record<string, { schedule: Array<{ opponent: string }> | null }>;
    };
    const names = new Map(directoryIndex().schools.map((s) => [s.slug, s.name]));
    const conference = new Set(MVAC_SCARLET.map((slug) => names.get(slug)));
    for (const sport of ['volleyball', 'basketball']) {
      const opponents = new Set(raw.sports[sport].schedule!.map((r) => r.opponent));
      for (const name of conference) expect(opponents.has(name!), `${sport} ${name}`).toBe(true);
    }
  });

  /*
   * The invariant the generator is anchored to produce: a score is only ever
   * printed on a day that has been.
   *
   * Checked as an ordering rather than against the clock, deliberately. The
   * file is static and drifts, and a test that read `new Date()` would turn
   * that expected drift into a red build. What must never be true, at any
   * distance from the generation, is a scored match dated after an unscored
   * one; that is a generator bug rather than staleness.
   */
  it('puts every result behind every fixture in the pasted schedules', async () => {
    const { loadDemo } = await load(committed());
    const demo = await loadDemo();

    for (const [sport, entry] of Object.entries(demo!.sports)) {
      const rows = entry.schedule ?? [];
      const scored = rows.filter((r) => r.score).map((r) => r.date);
      const ahead = rows.filter((r) => !r.score).map((r) => r.date);
      expect(scored.every((s) => ahead.every((a) => s < a)), sport).toBe(true);
    }

    // Volleyball owes results only when the autumn was on — and then both
    // kinds, because a school that wins everything reads as a brochure.
    const volleyball = demo!.sports.volleyball.schedule!;
    const results = volleyball.filter((r) => r.score);
    if (bornInSeason()) {
      expect(results.some((r) => r.score!.us > r.score!.them)).toBe(true);
      expect(results.some((r) => r.score!.us < r.score!.them)).toBe(true);
    } else {
      expect(results).toHaveLength(0);
    }
    expect(volleyball.some((r) => !r.score)).toBe(true);
  });

  /*
   * The file is generated in one sport-season and read in another, and the hub
   * prints "In season" or "Starts in November" out of its own fixed table. This
   * holds the committed dates to that table as it stood on the day they were
   * written — `generatedOn`, rather than the clock the suite happens to run on,
   * because the file is static and the point is what the generator produced.
   */
  it('never writes a season the hub would contradict', () => {
    // Read straight off the committed file rather than through loadDemo, which
    // carries the dates forward to today — what is being checked here is what
    // the generator wrote, on the day it wrote it.
    const raw = committed() as unknown as {
      generatedOn: string;
      sports: Record<string, { schedule: Array<{ date: string; score?: unknown }> | null }>;
    };
    const month = Number(raw.generatedOn.slice(5, 7));

    for (const [sport, entry] of Object.entries(raw.sports)) {
      for (const r of entry.schedule ?? []) {
        if (inSeason(sport, month)) continue;
        // Out of season on the day it was written, a sport may have no results
        // and may only be dated inside its own months.
        expect(!!r.score, `${sport} ${r.date}`).toBe(false);
        expect(inSeason(sport, Number(r.date.slice(5, 7))), `${sport} ${r.date}`).toBe(true);
      }
    }
  });

  /*
   * The generator is a .mjs script that cannot import this bundle's TypeScript,
   * so it keeps its own copy of the month table and this holds the two
   * together. Read out of the source text rather than imported, because
   * importing the script runs it — it resizes a crest and writes a file.
   */
  it('keeps the generator’s copy of the month table honest', () => {
    const src = readFileSync(new URL('../../scripts/build-demo.mjs', import.meta.url), 'utf8');
    const block = src.match(/const SPORT_MONTHS = \{([\s\S]*?)\n\};/);
    expect(block, 'SPORT_MONTHS is no longer where this test looks for it').not.toBeNull();

    const rows = [...block![1].matchAll(/^\s*(\w+): \[([\d, ]+)\],$/gm)];
    expect(rows.length).toBeGreaterThan(0);

    for (const [, sport, list] of rows) {
      expect(knownSports(), sport).toContain(sport);
      const copied = list.split(',').map((n) => Number(n.trim()));
      for (let month = 1; month <= 12; month += 1) {
        expect(copied.includes(month), `${sport} month ${month}`).toBe(inSeason(sport, month));
      }
    }
  });
});

/*
 * Carrying the calendar forward.
 *
 * The file is committed and then sits still while the world moves, and the
 * screen splits Played from Coming up on whether a game has a score rather than
 * on its date — so without this the demo starts listing last Tuesday's match as
 * coming up. These are the only tests here that name a day, and they name a
 * made-up one rather than reading the clock.
 *
 * The committed file bakes only pasted schedules, but the shim still moves a
 * baked season or forecast if a file carries one, so a couple of tests below
 * graft those on to keep that path honest.
 */
describe('the calendar, weeks after it was written', () => {
  const day = (iso: string) => new Date(`${iso}T00:00:00Z`);

  const everyDate = (demo: {
    seasons?: Record<string, { games: Array<{ date: string; result?: unknown }> }>;
    sports: Record<string, { schedule: Array<{ date: string; score?: unknown }> | null }>;
  }) => {
    const all: Array<[string, boolean]> = [];
    for (const season of Object.values(demo.seasons ?? {})) {
      for (const g of season.games) all.push([g.date, !!g.result]);
    }
    for (const entry of Object.values(demo.sports)) {
      for (const r of entry.schedule ?? []) all.push([r.date, !!r.score]);
    }
    return all;
  };

  const volleyballDates = (demo: {
    sports: Record<string, { schedule: Array<{ date: string }> | null }>;
  }) => demo.sports.volleyball.schedule!.map((r) => r.date);

  it('lands the split on today, however long the file has sat', async () => {
    const { loadDemo, shiftToNow } = await load(committed());
    const demo = await loadDemo();

    // Targets relative to the real clock, always ahead of it. loadDemo has
    // already carried the file to today, and the shim never drags a demo
    // backwards (a clock behind the file is left alone, by design), so a target
    // in the past is a case production can't reach.
    const ahead = (days: number) =>
      new Date(Date.now() + days * 86_400_000).toISOString().slice(0, 10);

    for (const when of [ahead(3), ahead(113), ahead(292), ahead(905)]) {
      const moved = shiftToNow(demo!, day(when));
      for (const [date, scored] of everyDate(moved)) {
        if (scored) expect(date < when, `${when}: ${date} has a score`).toBe(true);
        else expect(date >= when, `${when}: ${date} has no score`).toBe(true);
      }
    }
  });

  it('moves whole weeks, so a Tuesday match stays on a Tuesday', async () => {
    const { loadDemo, shiftToNow } = await load(committed());
    const demo = await loadDemo();
    const before = volleyballDates(demo!);
    const after = volleyballDates(shiftToNow(demo!, day('2027-06-30')));

    for (let i = 0; i < before.length; i += 1) {
      expect(day(after[i]).getUTCDay(), before[i]).toBe(day(before[i]).getUTCDay());
      const weeks = (day(after[i]).getTime() - day(before[i]).getTime()) / (7 * 86_400_000);
      expect(Number.isInteger(weeks), before[i]).toBe(true);
    }
  });

  it('moves every pasted schedule by the same amount', async () => {
    const { loadDemo, shiftToNow } = await load(committed());
    const demo = await loadDemo();
    const moved = shiftToNow(demo!, day('2027-06-30'));

    const deltas = new Set<number>();
    for (const [sport, entry] of Object.entries(demo!.sports)) {
      (entry.schedule ?? []).forEach((r, i) => {
        const after = moved.sports[sport].schedule![i].date;
        deltas.add(day(after).getTime() - day(r.date).getTime());
      });
    }
    expect(deltas.size).toBe(1);
  });

  it('carries a baked forecast and a baked season along with the rest', async () => {
    // Grafted on: the committed file bakes neither, but a file that does must
    // have them moved by the same weeks as everything else.
    const base = committed() as { slug: string; sports: { volleyball: { schedule: Array<{ date: string; score?: unknown }> } } };
    const next = base.sports.volleyball.schedule.find((r) => !r.score)!.date;
    const body = {
      ...base,
      weather: { date: next, code: 2, tempF: 63, precipChance: 20, windMph: 9, day: false, at: `${next}T19:00` },
      seasons: {
        [base.slug]: {
          school: { slug: base.slug, name: 'Springfield', city: 'New Middletown' },
          games: [{ week: 1, date: next, home: true, opponent: 'Brookfield' }],
          record: { won: 0, lost: 0, played: 0 },
        },
      },
    };
    const { loadDemo, shiftToNow } = await load(body);
    const demo = (await loadDemo())!;
    const moved = shiftToNow(demo, day('2027-01-02'));
    const movedNext = moved.sports.volleyball.schedule!.find((r) => !r.score)!.date;

    expect(moved.weather!.date).toBe(movedNext);
    expect(moved.weather!.at.startsWith(movedNext)).toBe(true);
    expect(moved.seasons[base.slug].games[0].date).toBe(movedNext);
  });

  it('leaves a file generated today exactly as it is', async () => {
    const born = (committed() as { generatedOn: string }).generatedOn;
    const { loadDemo, shiftToNow, weeksBehind } = await load(committed());
    const demo = await loadDemo();

    // Keyed on the day it was written rather than on its last result, because
    // a file written out of season has no results to key on.
    expect(weeksBehind(demo!, day(born))).toBe(0);
    expect(shiftToNow(demo!, day(born))).toBe(demo);
  });

  /*
   * The other kind of file: written between December and July, when the autumn
   * has not begun, so the generator writes every match as a fixture and nothing
   * as a result. It has no last-played day, and hinging on nothing used to mean
   * never moving — its fixtures would slide into the past one at a time and sit
   * there under "Coming up", which is the whole fault this is here to prevent.
   *
   * Made by stripping the scores off the committed file rather than by shipping
   * a second one, so it stays honest whichever half of the year the real file
   * was generated in.
   */
  const scoreless = () => {
    const raw = committed() as unknown as {
      sports: Record<string, { schedule: Array<Record<string, unknown>> | null }>;
    };
    for (const entry of Object.values(raw.sports)) {
      for (const r of entry.schedule ?? []) delete r.score;
    }
    return raw as unknown as Record<string, unknown>;
  };

  it('still moves a file with nothing played on it', async () => {
    const { loadDemo, shiftToNow, weeksBehind } = await load(scoreless());
    const demo = await loadDemo();

    for (const when of ['2027-03-01', '2027-11-11', '2030-01-20']) {
      const moved = shiftToNow(demo!, day(when));
      expect(weeksBehind(demo!, day(when)), when).toBeGreaterThan(0);
      for (const [date, scored] of everyDate(moved)) {
        expect(scored, `${when}: ${date}`).toBe(false);
        expect(date >= when, `${when}: ${date} is behind today`).toBe(true);
      }
    }
  });

  it('moves a scoreless file by whole weeks', async () => {
    const { loadDemo, shiftToNow } = await load(scoreless());
    const demo = await loadDemo();
    const before = volleyballDates(demo!);
    const after = volleyballDates(shiftToNow(demo!, day('2027-11-11')));

    for (let i = 0; i < before.length; i += 1) {
      const weeks = (day(after[i]).getTime() - day(before[i]).getTime()) / (7 * 86_400_000);
      expect(Number.isInteger(weeks), before[i]).toBe(true);
      expect(day(after[i]).getUTCDay(), before[i]).toBe(day(before[i]).getUTCDay());
    }
  });

  it('does not drag a scoreless file backwards either', async () => {
    const { loadDemo, weeksBehind } = await load(scoreless());
    expect(weeksBehind((await loadDemo())!, day('2020-01-01'))).toBe(0);
  });

  it('never drags a file backwards for a clock that is behind', async () => {
    const { loadDemo, weeksBehind } = await load(committed());
    expect(weeksBehind((await loadDemo())!, day('2020-01-01'))).toBe(0);
  });
});

describe('what the store guards ask for', () => {
  it('hangs the conference on football and on nothing else', async () => {
    const { demoRosterBody, DEMO_SLUG } = await load(committed());

    const football = (await demoRosterBody(DEMO_SLUG, 'football')) as Record<string, unknown>;
    expect(football.league).not.toBeNull();
    // Football's fixtures come from the directory, exactly as a real paid
    // school's do — there is nothing pasted for it.
    expect(football.schedule).toBeNull();

    const basketball = (await demoRosterBody(DEMO_SLUG, 'basketball')) as Record<string, unknown>;
    expect(basketball.league).toBeNull();
    expect(Array.isArray(basketball.schedule)).toBe(true);
  });

  it('answers for the demo school only', async () => {
    const { demoRosterBody, demoIdentity, demoWeather } = await load(committed());

    expect(await demoRosterBody('poland-seminary-poland', 'football')).toBeNull();
    expect(await demoIdentity('poland-seminary-poland')).toBeNull();
    expect(await demoWeather('poland-seminary-poland')).toBeNull();
  });

  it('answers nothing for a sport the school does not sell', async () => {
    const { demoRosterBody, DEMO_SLUG } = await load(committed());
    expect(await demoRosterBody(DEMO_SLUG, 'bowling')).toBeNull();
  });

  it('has no kept identity until the file has landed', async () => {
    const { keptDemoIdentity, loadDemo, DEMO_SLUG } = await load(committed());

    expect(keptDemoIdentity(DEMO_SLUG)).toBeNull();
    await loadDemo();
    expect(keptDemoIdentity(DEMO_SLUG)).not.toBeNull();
  });
});

/*
 * The guards, from the store side.
 *
 * This block deliberately does not mock ./supa the way rosterStore.test.ts
 * does. The demo has to work in a build with no Supabase variables at all —
 * which is exactly how CI runs — and the guards sit above the supaAvailable
 * gate precisely so that it does. Getting a roster back here, with no database
 * configured and no rpc mocked, is that claim being demonstrated rather than
 * asserted.
 */
describe('the store, in demo mode', () => {
  const stores = async () => {
    const { DEMO_SLUG } = await import('./demo');
    return {
      DEMO_SLUG,
      store: await import('./store'),
      rosterStore: await import('./rosterStore'),
    };
  };

  it('serves the roster and the identity out of the baked file, through the real validators', async () => {
    await load(committed());
    const { DEMO_SLUG, rosterStore } = await stores();

    const identity = await rosterStore.loadSchoolSports(DEMO_SLUG);
    expect(identity!.sports).toHaveLength(3);
    expect(identity!.colors).toEqual({ ground: '#0e0c0b', accent: '#f26722' });
    expect(identity!.logo).toMatch(/^data:image\/jpeg;base64,/);

    const roster = await rosterStore.loadSchoolRoster(DEMO_SLUG, 'volleyball');
    expect(roster!.players).toHaveLength(12);
    expect(roster!.schedule).toHaveLength(14);
    // Only football carries a conference, and this one is volleyball.
    expect(roster!.league).toBeNull();

    const football = await rosterStore.loadSchoolRoster(DEMO_SLUG, 'football');
    expect(football!.league!.name).toBe('MVAC Scarlet');
    expect(football!.league!.members).toHaveLength(7);
  });

  it('reads the season and the forecast from the directory, as a paid page does', async () => {
    const real = JSON.parse(readFileSync(dataFile('springfield-new-middletown'), 'utf8'));
    const forecast = {
      date: '2026-10-09',
      code: 3,
      tempF: 60,
      precipChance: 3,
      windMph: 7,
      day: true,
      at: '2026-10-09T23:00:00.000Z',
    };
    await load(committed(), {}, { 'springfield-new-middletown': forecast });
    const { DEMO_SLUG, store } = await stores();
    // A reader who follows the real Springfield in the directory and then opens
    // the demo — the one case where the jar rule below has anything to refuse.
    localStorage.setItem('oh.school', DEMO_SLUG);

    const season = await store.loadSeason(DEMO_SLUG);
    expect(season.school.name).toBe('Springfield');
    expect(season).toEqual(real);

    expect(await store.loadWeather(DEMO_SLUG)).toEqual(forecast);
    // And leaves nothing behind: a prospect's visit is not a school followed.
    expect(localStorage.getItem(`oh.weather.${DEMO_SLUG}`)).toBeNull();
  });

  it('leaves the kept-identity door where it was: null until the file lands', async () => {
    await load(committed());
    const { DEMO_SLUG, rosterStore } = await stores();

    expect(rosterStore.keptSchoolSports(DEMO_SLUG)).toBeNull();
    await rosterStore.loadSchoolSports(DEMO_SLUG);
    expect(rosterStore.keptSchoolSports(DEMO_SLUG)!.sports).toHaveLength(3);
  });

  it('refuses to remember a sport, so every prospect gets the hub', async () => {
    await load(committed());
    const { DEMO_SLUG, store } = await stores();
    const jar: Record<string, string> = {};
    vi.stubGlobal('localStorage', {
      getItem: (k: string) => jar[k] ?? null,
      setItem: (k: string, v: string) => {
        jar[k] = v;
      },
      removeItem: (k: string) => {
        delete jar[k];
      },
    });

    // What a seller tapping Volleyball to show a prospect does. It must leave
    // nothing behind: the hub is the screen the demo opens on, and the key
    // would outlive the visit anyway — choose()'s sweep only evicts the school
    // a reader was following, and nobody follows the demo.
    store.rememberSport(DEMO_SLUG, 'volleyball');
    expect(Object.keys(jar)).toEqual([]);
    expect(store.chosenSport(DEMO_SLUG)).toBeNull();

    // A key from some earlier build is not read either.
    jar[`oh.sport.${DEMO_SLUG}`] = 'basketball';
    expect(store.chosenSport(DEMO_SLUG)).toBeNull();
  });

  it('fills the whole MVAC Scarlet table from the directory, so the League tab draws', async () => {
    await load(committed());
    const { DEMO_SLUG, store, rosterStore } = await stores();

    const football = await rosterStore.loadSchoolRoster(DEMO_SLUG, 'football');
    const league = football!.league!;

    const { leagueTable } = await import('./leagueTable');
    const members = [DEMO_SLUG, ...league.members];
    const seasons = await Promise.all(members.map((m) => store.loadSeason(m)));
    const rows = leagueTable(seasons, members);

    // The whole conference or none of it — the rule School.tsx holds the tab
    // to. A demo that cannot fill its own table would ship a broken tab.
    expect(rows).toHaveLength(members.length);
    expect(rows.map((r) => r.slug)).toContain(DEMO_SLUG);
    expect(rows.find((r) => r.slug === 'western-reserve-berlin-center')!.name).toBe('Western Reserve');
  });
});

describe('a file that is not what it should be', () => {
  const mangled: Array<[string, unknown]> = [
    ['not an object', 'nope'],
    ['no slug', { ...committed(), slug: '' }],
    ['no sport names', { ...committed(), sportNames: [] }],
    ['a sport with no squad', (() => {
      const c = committed() as { sportNames: string[]; sports: Record<string, unknown> };
      return { ...c, sports: { ...c.sports, football: { players: [], schedule: null } } };
    })()],
    ['a sport the names promise and the file has not got', (() => {
      const c = committed() as { sportNames: string[] };
      return { ...c, sportNames: [...c.sportNames, 'lacrosse'] };
    })()],
    ['seasons that are not a map of seasons', { ...committed(), seasons: ['nope'] }],
    ['a baked season with no games', (() => {
      const c = committed() as { slug: string };
      return { ...c, seasons: { [c.slug]: { school: {}, games: null } } };
    })()],
  ];

  it.each(mangled)('reads %s as no demo rather than throwing', async (_label, body) => {
    const { loadDemo } = await load(body);
    await expect(loadDemo()).resolves.toBeNull();
  });

  it('drops a forecast it cannot trust without losing the demo with it', async () => {
    const { loadDemo } = await load({ ...committed(), weather: { date: '2026-09-25' } });
    const demo = await loadDemo();

    expect(demo).not.toBeNull();
    expect(demo!.weather).toBeNull();
  });

  it('reads a file that will not come at all as no demo', async () => {
    vi.resetModules();
    vi.stubGlobal('location', { pathname: '/oh/demo/', search: '' });
    vi.stubGlobal(
      'fetch',
      vi.fn(async () => {
        throw new Error('no signal');
      }),
    );
    const { loadDemo } = await import('./demo');
    await expect(loadDemo()).resolves.toBeNull();
  });
});
